/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaohuai_ndk_ConvertBitmap */

#ifndef _Included_com_xiaohuai_ndk_ConvertBitmap
#define _Included_com_xiaohuai_ndk_ConvertBitmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaohuai_ndk_ConvertBitmap
 * Method:    convertBitmap
 * Signature: (ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaohuai_ndk_ConvertBitmap_convertBitmap
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_xiaohuai_ndk_ConvertBitmap
 * Method:    blurBitmap
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaohuai_ndk_ConvertBitmap_blurBitmap
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_xiaohuai_ndk_ConvertBitmap
 * Method:    zoomBitmap
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_xiaohuai_ndk_ConvertBitmap_zoomBitmap
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
