/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaohuai_ndk_GetInt */

#ifndef _Included_com_xiaohuai_ndk_GetInt
#define _Included_com_xiaohuai_ndk_GetInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaohuai_ndk_GetInt
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xiaohuai_ndk_GetInt_getInt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
